# Generated by Django 4.2.4 on 2024-04-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0002_remove_theaters_movies"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seats",
            old_name="theater_id",
            new_name="theater_name",
        ),
        migrations.AlterField(
            model_name="seats",
            name="seat_number_booked",
            field=models.CharField(max_length=256),
        ),
    ]
