# Generated by Django 4.2.4 on 2024-04-20 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0003_rename_theater_id_seats_theater_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookedSeats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theater_name", models.CharField(max_length=256)),
                ("movie_name", models.CharField(max_length=256)),
                ("show_times", models.CharField(max_length=512)),
                ("seat_number_booked", models.CharField(max_length=256)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
